version: '3.9'

services:
  app:
    image: 'sha256:fecedb2345de5cd799dae572bcf540c8368a1d76c5e7e186602ac95ab57e455f'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=jkljkl
      - DB_URL=jdbc:postgresql://db:5432/postgres

    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jkljkl

